version: '3'

services:
  # Django web application
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
